## Numpy Array Operations

In [2]:
import numpy as np

In [3]:
# Basics from python
arr = np.array([1,2,3,4,5,6,7,8,9])
print("Basic Slicing",arr[2:7])
print("With step Slicing",arr[1:8:2])
print("Negative indexing",arr[-3])


Basic Slicing [3 4 5 6 7]
With step Slicing [2 4 6 8]
Negative indexing 7


In [4]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Specific element",arr_2d[1,2])# not allowed in regular python but numpy allows
print("Specific element",arr_2d[1]) # targeting row
print("Specific element",arr_2d[:,1]) #targeting column



Specific element 6
Specific element [4 5 6]
Specific element [2 5 8]


## Sorting

In [10]:
unsorted = np.array([3,1,4,6,5,2,2])
print("Sorted Array",np.sort(unsorted))
print("Original ",unsorted) 
arr_2d = np.array([[3,1],[1,2],[2,3]])
print("Sorted 2D array by Each Column",np.sort(arr_2d,axis=0))
print("Sorted 2D array by Each row",np.sort(arr_2d,axis=1))

Sorted Array [1 2 2 3 4 5 6]
Original  [3 1 4 6 5 2 2]
Sorted 2D array by Each Column [[1 1]
 [2 2]
 [3 3]]
Sorted 2D array by Each row [[1 3]
 [1 2]
 [2 3]]


## Filtering

In [11]:
num = np.array([1,2,3,4,5,6,7,8,9])
even_num = num[num%2 == 0]
print("Even Number Array",even_num)

Even Number Array [2 4 6 8]


## Filter with mask

In [12]:
mask = num > 5 
print("Numbers greater than 5",num[mask])


Numbers greater than 5 [6 7 8 9]


## Indexing and np.where()

In [16]:
indices = [0,2,4]
print(num[indices])
where = np.where(num>5)# where will have indice greater than 5
print("Num : ",num)
print("Where result \n",num[where])

condition = np.where(num>5,num*4,num) #it is equivalent to :-if(num>5){num*4}  else {num}
print(condition)
print("Original Num",num)

[1 3 5]
Num :  [1 2 3 4 5 6 7 8 9]
Where result 
 [6 7 8 9]
[ 1  2  3  4  5 24 28 32 36]
Original Num [1 2 3 4 5 6 7 8 9]


## Adding and removing data

In [18]:
arr1 =np.array([1,2,3])
arr2 =np.array([4,5,6])
merged = np.concatenate((arr1,arr2))
print(merged)



[1 2 3 4 5 6]


In [20]:
arr = np.array([1,2,3])
brr = np.array([4,5])
crr = np.array([7,8,9])
print("Compatibility shapes",arr.shape == brr.shape)


original = np.array([[1,2],[3,4]])
new  = np.array([[5,6]])
added_row = np.vstack((original,new))
print("original",original)
print("after vstack",added_row)
new_col = np.array( [ [7],[8]])
added_col = np.hstack((original,new_col))
print("After Adding col",added_col)

## delete
print("Original arr",arr)
deleted = np.delete(arr,2)
print("After delete of 2nd index",deleted)



Compatibility shapes False
original [[1 2]
 [3 4]]
after vstack [[1 2]
 [3 4]
 [5 6]]
After Adding col [[1 2 7]
 [3 4 8]]
Original arr [1 2 3]
After delete of 2nd index [1 2]
