## numpy array and basics  

In [1]:
import numpy as np
import time 

## creating array from list

In [3]:
arr_1d = np.array([1,2,3,4,5])
print("1D array",arr_1d)

aray_2d = np.array([[1,2,3],[1,2,3],[1,2,3]])
print("2D array",aray_2d)

1D array [1 2 3 4 5]
2D array [[1 2 3]
 [1 2 3]
 [1 2 3]]


## Numpy array vs Py List 


In [ ]:
py_list = [1,2,4]
print("Python list mul",py_list*2)

np_list = np.array([1,2,4])
print("Numpy list mul",np_list*2)


## checking eficiency 
start = time.time()
sec_py_list = [i*2 for i in range(100000)]
print("Python Multiplication took", time.time()-start)

start = time.time()
sec_np_list = np.arange(100000)
print("Numpy Multiplication took", time.time()-start)
#compare outputs :- numpy efficient






Python list mul [1, 2, 4, 1, 2, 4]
Numpy list mul [2 4 8]
Python Multiplication took 0.015166997909545898
Numpy Multiplication took 0.00036215782165527344


Creating array from scratch

In [4]:
zeros = np.zeros((3,4)) ## 3*4 array with all elements as zero  also ones method is present
print("zeros array:\n",zeros)

full = np.full((3,3),8)
print("full array\n",full) ##it allow creating array with any constant

random = np.random.random((2,3)) ##values from 0 to 1 
print("Random array \n",random)

sequence = np.arange(0,10,2)# 0 to 9
print("Sequence array",sequence)

zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
full array
 [[8 8 8]
 [8 8 8]
 [8 8 8]]
Random array 
 [[0.90129103 0.12799747 0.56073189]
 [0.04546358 0.49587566 0.91992148]]
Sequence array [0 2 4 6 8]


Tensor 

In [10]:
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("tensor",tensor)

tensor [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Properties

In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
print("Shape",arr.shape)
print("Dimensions",arr.ndim)
print("Size",arr.size)
print("Data Type",arr.dtype)
## Note :- we can create array with different data types but it is not ideal way to treate numpy arrays

Shape (2, 4)
Dimensions 2
Size 8
Data Type int64


Array Reshaping

In [6]:
arr = np.arange(12)
print("Array",arr)

reshape = arr.reshape((3,4))
print("Reshaped Array",reshape)

flatend = reshape.flatten()
print("Flattened Array",flatend)
print("Reshaped Array",reshape)

## returns view instead of array
raveled = reshape.ravel()
print("\n Raveled Array",raveled)

transposed = reshape.T
print("Transposed array",transposed)




Array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped Array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Raveled Array [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
