In [ ]:
import tensorflow as tf

## Basics

In [ ]:
tensor_zerod = tf.constant(4)
print(tensor_zerod)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
tensor_one = tf.constant([2.0, 4.0, 6.0])
print(tensor_one)

tf.Tensor([2. 4. 6.], shape=(3,), dtype=float32)


In [ ]:
tensor_two = tf.constant([[1, 2], [3, 4]])
print(tensor_two)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [ ]:
tensor_three = tf.constant([[[1,2,0],
                             [3,4,5]],
                            [[5,6,7],
                             [7,6,5]],
                            [[2,3,4],
                             [5,6,7]]
                            ],dtype=tf.float32)

print(tensor_three)

tf.Tensor(
[[[1. 2. 0.]
  [3. 4. 5.]]

 [[5. 6. 7.]
  [7. 6. 5.]]

 [[2. 3. 4.]
  [5. 6. 7.]]], shape=(3, 2, 3), dtype=float32)


In [ ]:
print(tensor_one.ndim)
print(tensor_three.ndim)

1
3


# Converting float to int

In [ ]:
#tf_float = tf.constant([1,2,3,4.5],dtype=tf.int32)
tf_float = tf.cast([1,2,3,4.5],dtype=tf.int32)
print (tf_float)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


## using Bool tensor


In [ ]:
casted_tensor = tf.cast(tensor_three,dtype=tf.bool)
print(casted_tensor) # only zero become false

tf.Tensor(
[[[ True  True False]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]

 [[ True  True  True]
  [ True  True  True]]], shape=(3, 2, 3), dtype=bool)


## Tensor String

In [ ]:
#tensor_str = tf.constant(["Hello",1,"World"]);
tensor_str = tf.constant(["Hello","World"]);
print(tensor_str)

tf.Tensor([b'Hello' b'World'], shape=(2,), dtype=string)


## Converting numpy array to tensor

In [ ]:
import numpy as np
np_array = np.array([1,3,4,5])
print(np_array)
converted_arr = tf.convert_to_tensor(np_array)
print(converted_arr)

[1 3 4 5]
tf.Tensor([1 3 4 5], shape=(4,), dtype=int64)
