## Some Methods of Tensor

In [12]:
import tensorflow as tf

In [13]:
eye_identity_mat =tf.eye(
    num_rows=3,
    num_columns=None,
     batch_shape=None,#[3,],
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_identity_mat)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


## Fill method

In [14]:
fill_tensor = tf.fill(
    [2,3],5 ,name=None
)
print(fill_tensor)

tf.Tensor(
[[5 5 5]
 [5 5 5]], shape=(2, 3), dtype=int32)


In [15]:
fill_tensor = tf.fill(
    [3,2,3],5 ,name=None
)
print(fill_tensor)

tf.Tensor(
[[[5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]]

 [[5 5 5]
  [5 5 5]]], shape=(3, 2, 3), dtype=int32)


## Ones Method

In [16]:
tf.ones(
    [2,3],
    dtype=tf.dtypes.float32,
    name=None
)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

## Slicing method

In [23]:
t1 = tf.constant([0, 1, 2, 3, 4, 5, 6, 7])
s1 = tf.slice(t1, begin=[1], size=[3])
print(s1)
print(t1[1:4]) # python slicing

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [21]:
t2 = tf.constant([[0, 1, 2],
                  [3, 4, 5],
                  [6, 7, 8]])
# Get the first row
first_row = tf.slice(t2, [0, 0], [1, tf.shape(t2)[1]])
print('First Row:\n', first_row)

# Get the second column
second_column = tf.slice(t2, [0, 1], [tf.shape(t2)[0], 1])
print('\nSecond Column:\n', second_column)

# Get the second and third columns
second_third_columns = tf.slice(t2, [0, 1], [tf.shape(t2)[0], 2])
print('\nSecond & Third Columns:\n', second_third_columns)

First Row:
 tf.Tensor([[0 1 2]], shape=(1, 3), dtype=int32)

Second Column:
 tf.Tensor(
[[1]
 [4]
 [7]], shape=(3, 1), dtype=int32)

Second & Third Columns:
 tf.Tensor(
[[1 2]
 [4 5]
 [7 8]], shape=(3, 2), dtype=int32)


In [34]:
tensor_3d = tf.constant([
    [
        [1,2,0],
        [3,5,-1]
    ], [
        [4,5,6],
        [7,8,9]
    ],
     [
        [10,11,12],
        [13,14,15]
    ]
])
print(tensor_3d)
print(tensor_3d[0:2,:,:])
#print(tensor_3d[[0,2],:,:])

tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]]], shape=(3, 2, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[ 4  5  6]
  [ 7  8  9]]], shape=(2, 2, 3), dtype=int32)


## Reshaping a Tensor

In [27]:
t4 = tf.constant([[1, 2, 3], [4, 5, 6]])
t5 = tf.reshape(t4,[6])
t6 = tf.reshape(t4,[3,2])
print(t5)
print(t6)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


## making Random Tensor

In [28]:
random_tensor = tf.random.normal(
    [3,3],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[ 1.1147697  -0.13216145 -0.4303303 ]
 [ 0.59982544  1.3150605  -0.7882221 ]
 [ 0.97381824 -0.94099987 -0.37201568]], shape=(3, 3), dtype=float32)


Maximum / Minimum

In [37]:
t1 = tf.constant([1,2,3,4,5])
t2 = tf.constant([6,7,8,1,4])
print(tf.math.argmax(t1))
print(tf.maximum(t1,t2))
print(tf.minimum(t1,t2))

tf.Tensor(4, shape=(), dtype=int64)
tf.Tensor([6 7 8 4 5], shape=(5,), dtype=int32)
tf.Tensor([1 2 3 1 4], shape=(5,), dtype=int32)
