In [2]:
import tensorflow as tf

In [3]:
x1 = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
x2 = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
if (x1.shape[1] == x2.shape[0]):
  mul = tf.matmul(x1,x2)
  print(mul)
else :
   print("Can't multiply")
print(x1@x2)


tf.Tensor(
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]], shape=(3, 3), dtype=int32)
tf.Tensor(
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]], shape=(3, 3), dtype=int32)


## Transpose

In [4]:
t1_transpose = tf.transpose(x1)
print(t1_transpose)

tf.Tensor(
[[1 4 7]
 [2 5 8]
 [3 6 9]], shape=(3, 3), dtype=int32)


In [5]:
tensor_three1 = tf.constant([[[1,2,0],
                             [3,4,5]
                            ],
                            [[5,6,7],
                             [7,6,5]
                             ],
                            [[2,3,4],
                             [5,6,7]
                            ]
                            ],dtype=tf.float32)
tensor_three2 = tf.constant([[[1,2,0],
                             [3,4,5],
                              [3,4,5]],
                            [[5,6,7],
                             [7,6,5],
                             [3,4,5]],
                            [[2,3,4],
                             [5,6,7],
                            [3,4,5]]
                            ],dtype=tf.float32)
print(tf.linalg.matmul(tensor_three1,tensor_three2))  #each 2d tensor * with each other at similar indices


tf.Tensor(
[[[  7.  10.  10.]
  [ 30.  42.  45.]]

 [[ 88.  94. 100.]
  [ 92.  98. 104.]]

 [[ 31.  40.  49.]
  [ 61.  79.  97.]]], shape=(3, 2, 3), dtype=float32)


##Sparse Tensor

In [6]:
sparse_tensor = tf.sparse.SparseTensor(indices=[[1,2],[3,3]],values=[1,2],dense_shape=[5,5])
print(sparse_tensor)

SparseTensor(indices=tf.Tensor(
[[1 2]
 [3 3]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 5], shape=(2,), dtype=int64))


Band Part

In [7]:
t1 = tf.constant([[1,2,3],
             [-2,-3,5],
             [-2,1,4]])
band_part = tf.linalg.band_part(t1,0,2)
print(band_part)

tf.Tensor(
[[ 1  2  3]
 [ 0 -3  5]
 [ 0  0  4]], shape=(3, 3), dtype=int32)


In [8]:
t1 = tf.constant([[1,2,3],
             [-2,-3,5],
             [-2,1,4]])
band_part = tf.linalg.band_part(t1,1,1)
print(band_part)

tf.Tensor(
[[ 1  2  0]
 [-2 -3  5]
 [ 0  1  4]], shape=(3, 3), dtype=int32)


## Inverse of Matrix

In [9]:
A = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]])

inv = tf.linalg.inv(A)
print(inv)
print(A@inv)##identity matrix

tf.Tensor(
[[-2.0000002   1.0000001 ]
 [ 1.5000001  -0.50000006]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 1.0000000e+00  0.0000000e+00]
 [-4.7683716e-07  1.0000002e+00]], shape=(2, 2), dtype=float32)


## SVD of matrix

In [10]:
A = tf.constant([[1, 2,3],
                 [3, 4,5],
                 [6, 7,8]
                 ],dtype=tf.float32)
s,v,d = tf.linalg.svd(A)
print(s)
print(v)
print(d)


tf.Tensor([1.4557620e+01 1.0372355e+00 3.8784324e-07], shape=(3,), dtype=float32)
tf.Tensor(
[[ 0.25000888  0.8370503  -0.4866646 ]
 [ 0.48517194  0.32667062  0.81110704]
 [ 0.83791643 -0.43889984 -0.32444268]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.46250868 -0.7870317   0.40824872]
 [ 0.5705688  -0.08823105 -0.8164965 ]
 [ 0.6786289   0.61057067  0.40824804]], shape=(3, 3), dtype=float32)


##EinSum Operator

In [11]:
A = tf.constant([1,2,3])
B = tf.constant([4,5,6])
tf.einsum('i,j->ij',A,B) # element wise dot product


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]], dtype=int32)>

In [12]:
#2-D
A = tf.constant([[1,2],[3,4]])
B = tf.constant([[5,6],[7,8]])
tf.einsum('ij,jk->ik',A,B) # same as matmul(A,B)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]], dtype=int32)>

In [13]:
tf.einsum("ij->ji",A) # same as tf.transpose(A)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

In [14]:
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[10, 20], [30, 40]])
tf.einsum("ij,ij->ij", A, B)  # same as tf.multiply(A, B)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 10,  40],
       [ 90, 160]], dtype=int32)>