In [2]:
import tensorflow as tf

## Expand_dims method

In [3]:
t1 = tf.constant([1,2,3,4])
print(t1.shape)
print(tf.expand_dims(t1, axis=0).shape)
print(tf.expand_dims(t1, axis=0))
print(tf.expand_dims(t1, axis=1).shape)
print(tf.expand_dims(t1, axis=1))
t1_expanded = tf.expand_dims(t1, axis=0)
print("Squeeze method o/p",tf.squeeze(t1_expanded,axis =0).shape)
print(tf.squeeze(t1_expanded))

(4,)
(1, 4)
tf.Tensor([[1 2 3 4]], shape=(1, 4), dtype=int32)
(4, 1)
tf.Tensor(
[[1]
 [2]
 [3]
 [4]], shape=(4, 1), dtype=int32)
Squeeze method o/p (4,)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


## concat Tensors

In [4]:
t1 = [[1,2,3],[4,5,6]]
t2 = [[7,8,9],[10,11,12]]
print(tf.concat([t1,t2],axis = 0))# row wise
print(tf.concat([t1,t2],axis = 1))# column concatenation
#

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]], shape=(2, 6), dtype=int32)


## Stack Tensors

In [5]:
t1 = [[1,2,3],[4,5,6]]
t2 = [[7,8,9],[10,11,12]]
print("Stack Result",tf.stack([t1,t2],axis = 0))# row wise
print("Concat Result",tf.concat([t1,t2],axis = 0))# row wise
print(tf.stack([t1,t2],axis = 1))# column concatenation
#


Stack Result tf.Tensor(
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)
Concat Result tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]], shape=(2, 2, 3), dtype=int32)


## Padding in Tensors

In [6]:
t1 = tf.constant([[1,2,3],[4,5,6]])
print(t1)
print(tf.pad(t1,[[1,1], # 1 row above & 1 row below
                 [2,2]],# 2 col left & 2 col right
             "CONSTANT",constant_values=0))


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[0 0 0 0 0 0 0]
 [0 0 1 2 3 0 0]
 [0 0 4 5 6 0 0]
 [0 0 0 0 0 0 0]], shape=(4, 7), dtype=int32)


## Gather Method

In [7]:
t1 = tf.constant([[1,2,3,4,5,6]])
print(tf.gather(t1,[0,1,2],axis = 1))
print(tf.gather(t1,[0,1],axis = 1))
#

tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
tf.Tensor([[1 2]], shape=(1, 2), dtype=int32)


In [8]:
# 2D Tensor
t1 = tf.constant([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(tf.gather(t1,[0,1],axis = 0))
print(tf.gather(t1,[0,1],axis = 1))

tf.Tensor(
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]], shape=(2, 6), dtype=int32)
tf.Tensor(
[[1 2]
 [7 8]], shape=(2, 2), dtype=int32)


In [9]:
tensor = tf.constant([[1, 2],
                      [3, 4]])

indices = tf.constant([[0, 0],
                       [1, 1]])

result = tf.gather_nd(tensor, indices)
print(result)

tf.Tensor([1 4], shape=(2,), dtype=int32)


## Ragged Tensors

In [10]:


rt = tf.ragged.constant([[1, 2, 3],
                         [4, 5],
                         [6],
                         [7, 8, 9, 10]])

print(rt)
rt[1]     # → [4, 5]
rt[3][2]  # → 9


<tf.RaggedTensor [[1, 2, 3], [4, 5], [6], [7, 8, 9, 10]]>


<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [11]:
# building ragged array from row lengths
print(tf.RaggedTensor.from_row_lengths(values=[1,2,3,4,5,6,7,8],
                                       row_lengths=[3,1,4,0]))


<tf.RaggedTensor [[1, 2, 3], [4], [5, 6, 7, 8], []]>


## Sparse Matrix

In [12]:
t1 = tf.sparse.SparseTensor(
    indices=[[0, 0], [1, 2]], #here non zero elements are present
    values=[1, 2],#values to be added at that indices
    dense_shape=[3, 4] #shape of sparse matrix
)
print(t1)

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64))


## String methods

In [17]:
tensor_string = tf.constant(["hello,","My self Abhishek","Gorde"])
print(tensor_string)
print(tf.strings.lower(tensor_string))
print(tf.strings.length(tensor_string))
print(tf.strings.join(tensor_string ,separator=' '))
print(tf.strings.unicode_decode(tensor_string,"UTF8"))

tf.Tensor([b'hello,' b'My self Abhishek' b'Gorde'], shape=(3,), dtype=string)
tf.Tensor([b'hello,' b'my self abhishek' b'gorde'], shape=(3,), dtype=string)
tf.Tensor([ 6 16  5], shape=(3,), dtype=int32)
tf.Tensor(b'hello, My self Abhishek Gorde', shape=(), dtype=string)
<tf.RaggedTensor [[104, 101, 108, 108, 111, 44],
 [77, 121, 32, 115, 101, 108, 102, 32, 65, 98, 104, 105, 115, 104, 101, 107],
 [71, 111, 114, 100, 101]]>
