In [ ]:
import tensorflow as tf

## Variables

In [15]:
x = tf.Variable(35)
y = tf.Variable(x + 5)
x.assign(100)
print(x)
print(y)
x.assign_sub(3)
print(x)


<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=100>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=40>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=97>


In [20]:
z = tf.Variable(tf.random.normal((3,3)))
print(z)
z.assign_sub(
  [[3,1,2],[3,1,2],[3,1,2]]
)
print(z)

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[-0.9610535 ,  0.34837142,  1.5431348 ],
       [-0.16227174,  1.5635965 , -0.14876758],
       [ 1.0393121 ,  0.47198215, -0.3173242 ]], dtype=float32)>
<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[-3.9610534, -0.6516286, -0.4568652],
       [-3.1622717,  0.5635965, -2.1487675],
       [-1.9606879, -0.5280179, -2.3173242]], dtype=float32)>


In [23]:
with tf.device('GPU:0'):
  a = tf.Variable([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])
  print(a)
  print(a.device)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>
/job:localhost/replica:0/task:0/device:CPU:0
